;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        LaTeX-babel-insert-hyphen
        LaTeX-insert-left-brace
        TeX-insert-backslash
        back-to-indentation-or-beginning
        end-of-visual-line
        ess-yank
        hydra--digit-argument
        hydra-multiple-cursors/mc/mark-all-like-this-and-exit
        hydra-multiple-cursors/mc/mark-next-like-this
        hydra-multiple-cursors/mc/mark-previous-like-this
        indent-for-tab-command
        org-cdlatex-math-modify
        org-self-insert-command
        ))

(setq mc/cmds-to-run-once
      '(
        pdf-view-mouse-set-region
        ))
