;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        LaTeX-babel-insert-hyphen
        LaTeX-insert-left-brace
        TeX-insert-backslash
        back-to-indentation-or-beginning
        backward-kill-char-or-region
        backward-kill-word-or-region
        downcase-region
        end-of-visual-line
        ess-yank
        hydra--digit-argument
        hydra-multiple-cursors/mc/mark-all-like-this-and-exit
        hydra-multiple-cursors/mc/mark-next-like-this
        hydra-multiple-cursors/mc/mark-previous-like-this
        indent-for-tab-command
        kill-visual-line
        org-cdlatex-math-modify
        org-end-of-line
        org-self-insert-command
        org-yank
        ))

(setq mc/cmds-to-run-once
      '(
        helm-M-x
        ignore
        lsp-ui-doc--handle-mouse-movement
        mouse-set-region
        org-export-dispatch
        pdf-view-mouse-set-region
        switch-window
        ))
